### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c703472 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c703472 with merge c703472...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8363b35 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8363b35 with merge 8363b35...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/163267127)
Approved by: japaric
Pushing 8363b359ca4b9bb1bad51dca514f17faef891e38 to master...

**Pull request merged**
