### PR TITLE
.travis: remove the webhook

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9d97ed3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9d97ed3 with merge 9d97ed3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/174106130)
Approved by: japaric
Pushing 9d97ed3e739dba4c9bff0a4733035a355a91b896 to master...

**Pull request merged**
