### PR TITLE
reexport Peripherals at the root for convenience

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 04353d4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 04353d4c5e89007ede594bc3efe49daef80981f0 with merge 9173fae4571efd21c41a6d175c42fb020f8d96d7...

**Comment by japaric** [comment]
Travis is having issues today. Tested locally. Merging.

**Pull request merged**
