### PR TITLE
Fix typo in ehprint! macro

### PR DESCRIPTION
**Pull request by schodet**
Misplaced colon.

### CODE REVIEW

**Comment by japaric** [comment]
Whoops! Thank you, @schodet.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e63e139 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e63e139 with merge e63e139...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/243871543?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing e63e13915d46d97dec4e87a1bd4a9e2ef36936f4 to master...

**Pull request merged**
