### PR TITLE
make `interrupt::enable` unsafe

### LINKED ISSUE #23: interrupt::enable() is safe to call inside interrupt::free()
This compiles:
```
fn main() {
    cortex_m::interrupt::free(|cs| {
        cortex_m::interrupt::enable();
    });
}
```
I suppose it's obvious why it's problematic...

### PR DESCRIPTION
**Pull request by japaric**
closes #23

cc @whitequark

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 70b9676 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 70b9676 with merge 70b9676...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/229769079?utm_source=github_status&utm_medium=notification)

**Comment by whitequark** [comment]
Unnecessary unsafe

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 46a7497 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 46a7497 with merge 46a7497...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/229770200?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 46a74971039373eb9642ce990fb9e093048f80a6 to master...

**Pull request merged**
