### PR TITLE
make this crate compile further for HOST

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3dc36ea has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3dc36ea with merge 3dc36ea...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/164557923)
Approved by: japaric
Pushing 3dc36eadb53a32f3fc713f744678eb08a2c50231 to master...

**Pull request merged**
