### PR TITLE
interrupt::free: don't let the token escape the critical section

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 03b94e6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 03b94e6 with merge 03b94e6...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/224013697)
Approved by: japaric
Pushing 03b94e691b282002912433266be4ba74df64c6d7 to master...

**Pull request merged**
