### PR TITLE
rename the types of core peripherals to UPPERCASE

### LINKED ISSUE #41: rename the types of core peripherals to UPPERCASE
to match the changes in svd2rust.

### PR DESCRIPTION
**Pull request by japaric**
closes #41

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3040369 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3040369 with merge 3040369...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/248867052?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 617a0bc has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 617a0bc with merge 617a0bc...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/248872522?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 617a0bc06f24b9305a266380044c4d802f458d1a to master...

**Pull request merged**
