### PR TITLE
add a Cargo feature, cm7-r0p1, to fix a Cortex-M7 BASEPRI erratum

### PR DESCRIPTION
**Pull request by japaric**
see japaric/cortex-m-rtfm#53 for background information

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4cd62a9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4cd62a9f75b2ca122dc7d26bacbcd38770cb3db1 with merge 6d01f2b0a61f63c61bdf9fca554a5ee1d5dbd1df...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/327712660?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f6ee6d0 has been approved by `japaric`

**Comment by japaric** [comment]
q

**Comment by homunkulus** [comment]
:hourglass: Testing commit f6ee6d0c49a5b87a51385dad625b372a4870d34d with merge 34f662106f327c25d00733773492cf80e9a4804a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/327715588?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 34f662106f327c25d00733773492cf80e9a4804a to master...

**Pull request merged**
