### PR TITLE
make the FPU API available only to targets that have a FPU

### LINKED ISSUE #49: Do not expose the FPU API for targets that don't have an FPU

### PR DESCRIPTION
**Pull request by japaric**
closes #49
cc @whitequark

### CODE REVIEW

**Comment by whitequark** [comment]
LGTM

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably 617a0bc) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 75c1148 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 75c1148 with merge 75c1148...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/248876777?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c960422 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c960422 with merge c960422...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/248883838?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing c9604220201f7c85f6b6fa07a3698552d2e3a281 to master...

**Pull request merged**
