### PR TITLE
use `cross`

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5341f8f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5341f8f with merge 5341f8f...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 39607ca has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 39607ca with merge 39607ca...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/187944866)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 476533c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 476533c with merge 476533c...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8879283 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8879283 with merge 8879283...

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3dbfae5 with merge 3dbfae5...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/187971909)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3bc81a2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3bc81a2 with merge 3bc81a2...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/187973205)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3fae77d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3fae77d with merge 3fae77d...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/187973799)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6fce8d4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6fce8d4 with merge 6fce8d4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/187974183)
Approved by: japaric
Pushing 6fce8d4c51f9178faf9f5dff8aebedaa59d2df78 to master...

**Pull request merged**
