### PR TITLE
don't expose registers clidr, ctr, ccsidr, csselr to ARMv6-M targets

### PR DESCRIPTION
**Pull request by japaric**
as these are only available on ARMv7-M devices

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c0e7dcb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c0e7dcb with merge c0e7dcb...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/248868362?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 58b5367 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 58b5367 with merge 04283fa...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/248873866?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 04283fa386201982cf2132f7be177383a685c9e5 to master...

**Pull request merged**
