### PR TITLE
make NVIC.set_priority and basepri::write unsafe

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e5fd02b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e5fd02b with merge e5fd02b...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/221197629)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5531a59 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5531a59 with merge 5531a59...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/221201809)
Approved by: japaric
Pushing 5531a594d3564c94734d36b067fa7bb4c4cb0bd6 to master...

**Pull request merged**
