### PR TITLE
add Exception

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 50779f2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 50779f2 with merge 50779f2...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/194268867)
Approved by: japaric
Pushing 50779f23d2bbe9ed5168c044ed63901bd2dd3ce7 to master...

**Pull request merged**
