### PR TITLE
add an example to the `itm::write_aligned` function; simplify `itm::write_all`

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 51d92fb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 51d92fb with merge 51d92fb...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f1bdfaa has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f1bdfaa with merge f1bdfaa...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit fc9e676 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit fc9e676 with merge fc9e676...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d5eb639 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d5eb639 with merge d5eb639...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a899f3b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a899f3b with merge a899f3b...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c3e49db has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c3e49db with merge c3e49db...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/237606673?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit db27f0b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit db27f0b with merge db27f0b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/237624829?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing db27f0b60c851db013aa9a730b9b4f71ce25f004 to master...

**Pull request merged**
