### PR TITLE
enable cache and drop target files

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 01464c2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 01464c2 with merge 01464c2...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 320a692 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 320a692 with merge 320a692...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 66a1769 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 66a1769 with merge 66a1769...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/165794216)
Approved by: japaric
Pushing 66a17696addb7bca7c94f2ed605e53fc28e76263 to master...

**Pull request merged**
