### PR TITLE
add a StackFrame data structure

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a365370 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a365370 with merge a365370...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/165061721)
Approved by: japaric
Pushing a36537033a9242731d46fd79ab7285a7e3a85512 to master...

**Pull request merged**
