### PR TITLE
default exception handler: identify the exception that's being serviced

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8394581 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8394581 with merge 8394581...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/210290620)
Approved by: japaric
Pushing 83945819af5a724ba9175fdc5e22b7c854a0fc14 to master...

**Pull request merged**
