### PR TITLE
map asm! ops to unimplemented! on non ARM targets

### PR DESCRIPTION
**Pull request by japaric**
closes #63
cc @hannobraun

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f79f4b7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f79f4b73fb19ad537669d71f3f567aad9810a8f5 with merge bdc7ca96c5593e410c8f49025d2b0fced7607a4d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/320718911?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing bdc7ca96c5593e410c8f49025d2b0fced7607a4d to master...

**Pull request merged**
