### PR TITLE
docs: unhide `Peripheral::steal` method

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 86d4449 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 86d4449beb170fdd00012692b3ba3b07ebd5897c with merge b9ac0afb240123653c1aa3c7c9c8e22e04463422...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 385e0cd has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 385e0cda4893abce71a42633b953b7bee42b5947 with merge 74cb12e105346d11d57ef653669748d28d96c05e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/313910262?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/313910262?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 74cb12e105346d11d57ef653669748d28d96c05e to master...

**Pull request merged**
