### PR TITLE
Add nop function

### PR DESCRIPTION
**Pull request by thejpster**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ee88607 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ee88607 with merge ee88607...

**Comment by japaric** [comment]
Thank you, @thejpster!

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/167961955)
Approved by: japaric
Pushing ee886077368c096669f18821288bc0cba13dd4dc to master...

**Pull request merged**
