### PR TITLE
turn peripherals into scoped singletons

### PR DESCRIPTION
**Pull request by japaric**
See this RFC for details: japaric/svd2rust#157

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9bab417 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9bab4175eb4120612e07470d060d6aca3b5edfd5 with merge e5c7f14862c5d0dd65d471a940261e419917c086...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/313900346?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b7a627c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b7a627cd986cb05e71c456782daaee4f47e26ede with merge 5c75a4e84b3f13d2b3e9a73f8b7f2e0eaf66012e...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0b45ea4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0b45ea4bd486565da5d78793dcb4718afb4f4387 with merge ce5bee6e37b4127040224523a1af85c275401a18...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/313902097?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/313902097?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing ce5bee6e37b4127040224523a1af85c275401a18 to master...

**Pull request merged**
