### PR TITLE
add Dwt.enable_cycle_counter

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d9445fb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d9445fb with merge d9445fb...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/235252160?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing d9445fbf4a411f979248b17085749520620d5e19 to master...

**Pull request merged**
