### PR TITLE
move non Cortex-M specific bits into a crate

### LINKED ISSUE #50: Move generic device stuff out of cortex-m
via https://github.com/japaric/svd2rust/pull/117

`Peripheral`, and maybe some other structs, aren't really Cortex-M specific. svd2rust currently relies on this crate just for that struct, but if it generates, say, some Rust code for a Cortex-A target instead, it still needs `Peripheral` but nothing else.

First thought that comes to mind would be to move `Peripheral` (and friends?) out into a separate crate, and have svd2rust and cortex-m rely on that generic crate instead. But, I'm sure there are many ways to do it.

Thoughts?

### PR DESCRIPTION
**Pull request by japaric**
closes #50

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d14589a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d14589a with merge d14589a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/250934186?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing d14589a9836aa625fd9a6d7107d48a7429525b21 to master...

**Pull request merged**
