### PR TITLE
Add an API to set FPU access mode

### PR DESCRIPTION
**Pull request by whitequark**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0e3dd2d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0e3dd2d with merge 0e3dd2d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/229766954?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 0e3dd2df58e52f9af80e47327a62a83511e010f9 to master...

**Pull request merged**
