### PR TITLE
Fix bitmasks in peripheral::Scb::fpu_access_mode

### PR DESCRIPTION
**Pull request by whitequark**

### CODE REVIEW

**Comment by japaric** [comment]
Thanks @whitequark.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6b5c4cf has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6b5c4cf with merge 6b5c4cf...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/231750138?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 6b5c4cf602215fec400e4c9136feb3e271877b22 to master...

**Pull request merged**
