### PR TITLE
hide ARMv7-M only peripherals on thumbv6m-none-eabi

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d4de1c2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d4de1c2d45e64e1c67c115c573a9a0ed1252cd94 with merge 76fca9facd887f5f06ae544928443879827bf01f...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/329161768?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a8962d4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a8962d44d46ef3c16b3e5fb645fead4731cd2b24 with merge d52b84c6e7f942814b270db5606c7e5a94fbc99a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/329169901?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing d52b84c6e7f942814b270db5606c7e5a94fbc99a to master...

**Pull request merged**
