### PR TITLE
inline all the functions in the asm module

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2e534ea has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2e534ea with merge 2e534ea...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/239696404?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 2e534ea4d85f321a4175a58fc77455380360ca9d to master...

**Pull request merged**
