### PR TITLE
fix itm::write_all

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 14851f2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 14851f2 with merge 14851f2...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/237740008?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 14851f2ad78b5675cb253915ce21e58dfb75a020 to master...

**Pull request merged**
