### PR TITLE
tweak CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 75e0800 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 75e0800 with merge 75e0800...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/185784034)
Approved by: japaric
Pushing 75e08005a4c7ad0b13fa7d75ef67f2ce2c0a82e8 to master...

**Pull request merged**
