### PR TITLE
derive Clone, Copy and Debug for more structs / enums

### PR DESCRIPTION
**Pull request by japaric**
cc @whitequark

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2b256bf has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2b256bf with merge 2b256bf...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/232657318?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 2b256bf82b09be437b1053739c36a87d6b4662db to master...

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
