### PR TITLE
Fix asm

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 72491cc has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 72491cc with merge 72491cc...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/165035934)
Approved by: japaric
Pushing 72491cc3f73930ecc86f457f808836eb32252378 to master...

**Pull request merged**
