### PR TITLE
v0.4.0

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 56f0804 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 56f08040b22da908993cedddeababe4a7ff9d744 with merge e0abee8ad6d97e3d6f29321830dc8759a3acbef3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m/builds/329201220?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing e0abee8ad6d97e3d6f29321830dc8759a3acbef3 to master...

**Pull request merged**
